### ISSUE TITLE
DNS queries insecure

### ISSUE THREAD

**Issue by shokohsc** [k8s-at-home/pod-gateway#40]
# Details

**What steps did you take and what happened:**

Basically, using this pod-gateway settings.sh:
```
#!/bin/sh
# Generated by pod-gateway
DNS_LOCAL_CIDRS="local"
VPN_BLOCK_OTHER_TRAFFIC="true"
VPN_INTERFACE="tun0"
VPN_LOCAL_CIDRS="10.233.0.0/16"
VPN_TRAFFIC_PORT="443"
VXLAN_GATEWAY_FIRST_DYNAMIC_IP="20"
VXLAN_ID="42"
VXLAN_IP_NETWORK="172.16.0"
```
and this pod content:
```
...
containers:
- name: pod-gateway
  image: ghcr.io/k8s-at-home/pod-gateway:v1.7.0
  command:
    - /bin/gateway_sidecar.sh
  securityContext:
    capabilities:
      add:
      - NET_ADMIN
  ports:
    - name: dhcp
      containerPort: 67
      protocol: UDP
    - name: foo
      containerPort: 8472
      protocol: UDP
  startupProbe:
    exec:
      command:
      - ip
      - a
      - s
      - tun0
  readinessProbe:
    exec:
      command:
      - ip
      - a
      - s
      - tun0
  livenessProbe:
    exec:
      command:
        - nc
        - -zv
        - google.com
        - "443"
  resources:
    limits:
      cpu: 100m
      memory: 64M
    requests:
      cpu: 10m
      memory: 64M
  volumeMounts:
    - name: config
      mountPath: /config
      readOnly: true
...
```
 dnsmasq dnssec returns insecure results for every domain request forwarded

**What did you expect to happen:**

I expected to have dnsmasq.d logs show secure results

**Anything else you would like to add:**

Should I overwrite the gateway-sidecar.sh to remove dnssec ? https://github.com/k8s-at-home/pod-gateway/blob/main/bin/gateway_sidecar.sh#L36

**Additional Information:**

Each cluster node has some host specific dns configuration, as in:

```
nameserver 127.0.0.53
options edns0 trust-ad
search default.svc.cluster.local svc.cluster.local
```

Would that conflict with this project ?
